### ISSUE TITLE
Code Style

### ISSUE THREAD

**Issue by fuchsto** [rskletza/c3particles#2]
I noticed some bad habits in code style, like missing curly braces for single-statement blocks:

~~~c++
if (cond)
   stuff();
else
   otherstuff();
~~~

... and some other no-nos.
Now, we want you to look good in your code, so have a look at google's [c++ style guide](https://google.github.io/styleguide/cppguide.html), they also provide tools to check your code against it, called [cpplint](https://github.com/google/styleguide/tree/gh-pages/cpplint).

**Comment by rskletza** [comment]
introduced .clang-format to format code
